apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.matburt.mobileorg"
        minSdkVersion 17
        targetSdkVersion 24
        versionCode 1
        versionName "2.0.2"
    }

    signingConfigs {
        release {
            storeFile file('../mobileorg-release.keystore')
            storePassword 'lujun9972'
            keyAlias 'mobileorg'
            keyPassword 'lujun9972'
        }
    }

    lintOptions {
        disable 'MissingTranslation', 'ExtraTranslation'
        abortOnError false
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation files('libs/actionbarsherlock-4.4.0-patched.aar')
    implementation 'com.jcraft:jsch:0.1.50'
    implementation 'com.android.support:support-v4:25.4.0'
    implementation 'com.android.support:recyclerview-v7:25.4.0'
    implementation project(':libraries:locale')
}
